### ISSUE TITLE
When Displaying a MessageBox this can happen !

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-4.7#29]
```
---------------------------
Unhandled Application Exception
---------------------------

System.NullReferenceException: Object reference not set to an instance of an object.
   at ComponentFactory.Krypton.Toolkit.KryptonMessageBox.UpdateMessageSizing(IWin32Window showOwner)
   at ComponentFactory.Krypton.Toolkit.KryptonMessageBox.UpdateSizing(IWin32Window showOwner)
   at ComponentFactory.Krypton.Toolkit.KryptonMessageBox.InternalShow(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, HelpInfo helpInfo)
   at ComponentFactory.Krypton.Toolkit.KryptonMessageBox.Show(String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon)
   atProgramBase.Start()
---------------------------
OK   
---------------------------

```

**Comment by Smurf-IV** [comment]
I suspect it has something to do with the `this` being passed in for the owner being null But I am unsure.

**Comment by Wagnerp** [comment]
May need a try/catch statement in the `KryptonMessageBox` code to prevent nullable failovers. Is this happening since I've restructured the `source` folder?

**Comment by Wagnerp** [comment]
Ok, by the way, I've redone the `Palette Upgrade Tool` that was present in the commercial version before Phil Wright made it open source. It is not currently in the original repo. Might be useful for the extended toolkit project.

**Comment by Smurf-IV** [comment]
Tested - Now fixed :-)
